---
title: "Governor Elections 4th (v0)" 
author: "sw1kwon"
date: "07/15/2025"
draft: false
---

# 4th_2006

## Raw Data

In [1]:
# =============================================================================
# 4대 지방선거 데이터 전처리 함수들
# =============================================================================

import pandas as pd
import re
import requests
import tempfile
import os

def convert_github_url_to_raw(github_url):
    """
    깃허브 blob URL을 raw URL로 변환
    """
    if '/blob/' in github_url:
        return github_url.replace('/blob/', '/raw/')
    return github_url


def process_4th_governor_election(
    file_path_or_url,
    header_rows=(4, 6),
    filter_column=None,
    filter_value=None
):
    """
    선거 데이터 전처리 함수 (17대 대선 코드 패턴 적용)
    """
    # URL인 경우 처리
    if file_path_or_url.startswith(('http://', 'https://')):
        # GitHub URL 변환
        if 'github.com' in file_path_or_url:
            file_path_or_url = convert_github_url_to_raw(file_path_or_url)

        # 임시 파일로 다운로드
        with tempfile.NamedTemporaryFile(delete=False, suffix=".xls") as tmp:
            response = requests.get(file_path_or_url)
            response.raise_for_status()
            tmp.write(response.content)
            tmp_path = tmp.name

        try:
            df_raw = pd.read_excel(tmp_path, header=None)
        finally:
            os.remove(tmp_path)
    else:
        # 로컬 파일인 경우
        df_raw = pd.read_excel(file_path_or_url, header=None)

    # 헤더 처리
    start_idx = header_rows[0] - 1
    end_idx = header_rows[1] - 1

    header_rows_data = []
    for i in range(start_idx, end_idx + 1):
        header_rows_data.append(df_raw.iloc[i].fillna('').astype(str))

    # 컬럼명 생성
    new_columns = []
    for col_idx in range(len(header_rows_data[0])):
        parts = [row_data[col_idx] for row_data in header_rows_data if row_data[col_idx] != '']
        new_columns.append('_'.join(parts) if parts else f'column_{col_idx}')

    # 데이터 추출
    data_start_idx = end_idx + 1
    df = df_raw.iloc[data_start_idx:].copy()
    df.columns = new_columns
    df = df.reset_index(drop=True)

    print(f"헤더 행: {header_rows[0]}행 ~ {header_rows[1]}행")
    print(f"생성된 컬럼 수: {len(new_columns)}")
    print(f"데이터 행 수: {len(df)}")

    # 필터링
    if filter_column and filter_value:
        matching_col = None
        for col in df.columns:
            if filter_column in col:
                matching_col = col
                break

        if matching_col:
            print(f"\n'{filter_column}' 컬럼 발견: {matching_col}")
            filtered_df = df[df[matching_col] == filter_value].copy()
            print(f"필터링 전: {len(df)}행 → 필터링 후: {len(filtered_df)}행")
            return filtered_df
        else:
            print(f"\n경고: '{filter_column}'을 포함하는 컬럼을 찾을 수 없습니다.")

    return df


def process_4th_governor_election_batch(user, repo, folder):
    """
    4대 지방선거 시도지사 선거 데이터 일괄 처리 함수

    Parameters:
    -----------
    user : str
        GitHub 사용자명
    repo : str
        GitHub 저장소명
    folder : str
        데이터가 있는 폴더 경로

    Returns:
    --------
    pd.DataFrame
        병합된 선거 데이터

    Example:
    --------
    df4th = process_4th_governor_election_batch(
        user="checkdroid",
        repo="korean-elections",
        folder="original/Local_Elections_Governor/4th_2006/11_서울"
    )
    """
    print(f"4대 지방선거 데이터 일괄 처리 시작")
    print(f"저장소: {user}/{repo}")
    print(f"폴더: {folder}")
    print("-" * 60)

    # ================================
    # 1. GitHub API로 파일 목록 가져오기
    # ================================
    api_url = f"https://api.github.com/repos/{user}/{repo}/contents/{folder}"

    try:
        response = requests.get(api_url)
        response.raise_for_status()
        files = response.json()
        print(f"폴더에서 {len(files)}개 파일 발견")
    except Exception as e:
        print(f"API 요청 실패: {e}")
        return None

    # ================================
    # 2. 각 .xls 파일 처리
    # ================================
    processed_dfs = []
    success_count = 0
    failed_files = []

    for file_info in files:
        file_name = file_info["name"]

        # .xls 파일만 처리
        if not file_name.endswith(".xls"):
            continue

        # 파일명에서 지역명 추출 (예: "1101_종로구_서울특별시.xls" → "종로구")
        match = re.match(r"^\d+_([^_]+)_[^_]+\.xls$", file_name)
        if not match:
            print(f"파일명 패턴 불일치, 무시: {file_name}")
            continue

        region = match.group(1)
        print(f"\n처리 중: {file_name} (지역: {region})")

        # raw URL 생성
        raw_url = f"https://raw.githubusercontent.com/{user}/{repo}/main/{folder}/{file_name}"

        try:
            # 임시 파일로 다운로드 후 처리
            with tempfile.NamedTemporaryFile(delete=False, suffix=".xls") as tmp:
                response = requests.get(raw_url)
                response.raise_for_status()
                tmp.write(response.content)
                tmp_path = tmp.name

            # 개별 파일 전처리
            df_region = process_4th_governor_election(
                tmp_path,
                header_rows=(4, 6),
                filter_column='읍면동명',
                filter_value='합계'
            )

            # 지역명 추가
            if df_region is not None and not df_region.empty:
                df_region.insert(0, '구시군명', region)
                processed_dfs.append(df_region)
                success_count += 1
                print(f"  ✓ 완료: {df_region.shape[0]}행 추가")
            else:
                print(f"  ⚠ 경고: 데이터가 비어있거나 필터링 결과 없음")
                failed_files.append(file_name)

            # 임시 파일 삭제
            os.remove(tmp_path)

        except Exception as e:
            print(f"  ✗ 오류 발생: {type(e).__name__}: {str(e)}")
            failed_files.append(file_name)
            # 임시 파일이 있다면 삭제
            if 'tmp_path' in locals() and os.path.exists(tmp_path):
                os.remove(tmp_path)
            continue

    # ================================
    # 3. 모든 DataFrame 병합
    # ================================
    print("\n" + "=" * 60)
    if processed_dfs:
        df_combined = pd.concat(processed_dfs, ignore_index=True)
        print(f"일괄 처리 완료:")
        print(f"  - 성공: {success_count}개 파일")
        print(f"  - 실패: {len(failed_files)}개 파일")
        if failed_files:
            print(f"  - 실패 파일: {', '.join(failed_files[:5])}")
            if len(failed_files) > 5:
                print(f"    ... 외 {len(failed_files)-5}개")
        print(f"  - 최종 크기: {df_combined.shape[0]}행 x {df_combined.shape[1]}열")
        return df_combined
    else:
        print("처리된 파일이 없습니다.")
        return None

## Seoul

In [2]:
seoul_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/11_서울"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/11_서울
------------------------------------------------------------
폴더에서 25개 파일 발견

처리 중: 1101_종로구_서울특별시.xls (지역: 종로구)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 29

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 29행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1102_중구_서울특별시.xls (지역: 중구)
WARNING *** file size (14357) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1103_용산구_서울특별시.xls (지역: 용산구)
WARNING *** file size (16823) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 30

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 30행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1104_성동구_서울특별시.xls (지역: 성동구)
WARNING *** file size (16956) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 30

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 30행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1105_광진구_서울특별시.xls (지역: 광진구)
WARNING *** file size (15432) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 26

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 26행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1106_동대문구_서울특별시.xls (지역: 동대문구)
WARNING *** file size (20441) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 43

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 43행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1107_중랑구_서울특별시.xls (지역: 중랑구)
WARNING *** file size (17001) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 30

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 30행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1108_성북구_서울특별시.xls (지역: 성북구)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 47

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 47행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1109_강북구_서울특별시.xls (지역: 강북구)
WARNING *** file size (15813) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 27

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 27행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1110_도봉구_서울특별시.xls (지역: 도봉구)
WARNING *** file size (15032) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 25

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 25행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1111_노원구_서울특별시.xls (지역: 노원구)
WARNING *** file size (18773) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 34

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 34행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1112_은평구_서울특별시.xls (지역: 은평구)
WARNING *** file size (17056) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 30

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 30행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1113_서대문구_서울특별시.xls (지역: 서대문구)
WARNING *** file size (17350) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 31

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 31행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1114_마포구_서울특별시.xls (지역: 마포구)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 34

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 34행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1115_양천구_서울특별시.xls (지역: 양천구)
WARNING *** file size (17050) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 30

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 30행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1116_강서구_서울특별시.xls (지역: 강서구)
WARNING *** file size (17950) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 32

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 32행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1117_구로구_서울특별시.xls (지역: 구로구)
WARNING *** file size (16673) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 29

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 29행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1118_금천구_서울특별시.xls (지역: 금천구)
WARNING *** file size (13787) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 22

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 22행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1119_영등포구_서울특별시.xls (지역: 영등포구)
WARNING *** file size (17830) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 32

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 32행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1120_동작구_서울특별시.xls (지역: 동작구)
WARNING *** file size (17056) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 30

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 30행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1121_관악구_서울특별시.xls (지역: 관악구)
WARNING *** file size (20651) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 43

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 43행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1122_서초구_서울특별시.xls (지역: 서초구)
WARNING *** file size (16199) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 28

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 28행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1123_강남구_서울특별시.xls (지역: 강남구)
WARNING *** file size (20390) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 43

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 43행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1124_송파구_서울특별시.xls (지역: 송파구)
WARNING *** file size (20553) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 43

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 43행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 1125_강동구_서울특별시.xls (지역: 강동구)
WARNING *** file size (17386) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 20
데이터 행 수: 31

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 31행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 25개 파일
  - 실패: 0개 파일
  - 최종 크기: 25행 x 21열

In [3]:
seoul_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n강금실,한나라당\n오세훈,민주당\n박주선,민주노동당\n김종철,...,시민당\n이귀선,한미준\n이태희,무소속\n백승원,column_13,계,무효\n투표수,기권수,column_17,column_18,column_19
0,종로구,NaN,합계,"134,603",NaN,"71,240","19,369","41,992","6,460","1,945",...,110,89,265,NaN,"70,466",774,"63,363",NaN,NaN,0.0
1,중구,NaN,합계,"107,164",NaN,"55,369","15,382","32,708","4,609","1,455",...,193,113,212,NaN,"54,858",511,"51,795",NaN,NaN,0.0
2,용산구,NaN,합계,"187,461",NaN,"95,809","26,087","58,427","6,970","2,632",...,152,124,319,NaN,"95,029",780,"91,652",NaN,NaN,0.0
3,성동구,NaN,합계,"266,956",NaN,"131,927","35,842","77,631","11,971","3,975",...,165,153,488,NaN,"130,686","1,241","135,029",NaN,NaN,0.0
4,광진구,NaN,합계,"293,308",NaN,"141,079","39,716","83,209","11,693","4,070",...,228,121,443,NaN,"140,012","1,067","152,229",NaN,NaN,0.0
5,동대문구,NaN,합계,"305,097",NaN,"153,571","40,952","92,583","12,817","4,344",...,231,171,509,NaN,"152,089","1,482","151,526",NaN,NaN,0.0
6,중랑구,NaN,합계,"332,783",NaN,"155,626","41,950","94,016","12,084","4,711",...,236,177,656,NaN,"154,367","1,259","177,157",NaN,NaN,0.0
7,성북구,NaN,합계,"369,617",NaN,"183,552","52,218","107,844","14,592","5,856",...,191,239,620,NaN,"182,138","1,414","186,065",NaN,NaN,0.0
8,강북구,NaN,합계,"280,448",NaN,"133,939","37,446","75,788","13,997","4,146",...,207,187,577,NaN,"132,776","1,163","146,509",NaN,NaN,0.0
9,도봉구,NaN,합계,"291,852",NaN,"147,638","41,460","88,101","11,290","4,542",...,113,108,450,NaN,"146,624","1,014","144,214",NaN,NaN,0.0
10,노원구,NaN,합계,"465,546",NaN,"239,926","70,050","140,438","16,712","8,584",...,207,346,851,NaN,"238,197","1,729","225,620",NaN,NaN,0.0
11,은평구,NaN,합계,"367,295",NaN,"173,479","50,411","100,572","14,237","5,172",...,198,155,693,NaN,"172,048","1,431","193,816",NaN,NaN,0.0
12,서대문구,NaN,합계,"277,490",NaN,"137,876","40,422","80,851","10,224","4,145",...,126,113,402,NaN,"136,765","1,111","139,614",NaN,NaN,0.0
13,마포구,NaN,합계,"312,630",NaN,"154,442","46,057","88,818","11,486","5,020",...,409,178,669,NaN,"153,164","1,278","158,188",NaN,NaN,0.0
14,양천구,NaN,합계,"374,034",NaN,"193,234","52,456","117,983","13,345","5,853",...,251,439,772,NaN,"191,852","1,382","180,800",NaN,NaN,0.0
15,강서구,NaN,합계,"430,027",NaN,"211,567","59,119","126,548","15,191","6,529",...,241,477,888,NaN,"209,771","1,796","218,460",NaN,NaN,0.0
16,구로구,NaN,합계,"327,895",NaN,"164,398","47,384","96,508","11,960","5,506",...,143,171,542,NaN,"162,871","1,527","163,497",NaN,NaN,0.0
17,금천구,NaN,합계,"199,986",NaN,"97,796","28,326","54,833","8,932","3,630",...,153,129,407,NaN,"96,842",954,"102,190",NaN,NaN,0.0
18,영등포구,NaN,합계,"325,010",NaN,"163,818","45,339","98,766","11,705","4,897",...,325,188,588,NaN,"162,393","1,425","161,192",NaN,NaN,0.0
19,동작구,NaN,합계,"328,129",NaN,"166,416","48,416","95,686","14,475","5,034",...,149,158,526,NaN,"165,049","1,367","161,713",NaN,NaN,0.0
20,관악구,NaN,합계,"431,791",NaN,"210,854","66,667","110,710","21,654","8,260",...,235,177,780,NaN,"209,279","1,575","220,937",NaN,NaN,0.0
21,서초구,NaN,합계,"316,852",NaN,"164,426","33,010","117,293","9,278","2,861",...,102,98,382,NaN,"163,569",857,"152,426",NaN,NaN,0.0
22,강남구,NaN,합계,"433,889",NaN,"216,768","39,314","160,646","10,696","3,784",...,91,80,588,NaN,"215,765","1,003","217,121",NaN,NaN,0.0
23,송파구,NaN,합계,"467,011",NaN,"237,313","57,435","155,062","15,940","5,676",...,171,150,631,NaN,"235,799","1,514","229,698",NaN,NaN,0.0
24,강동구,NaN,합계,"356,774",NaN,"175,779","43,062","112,747","12,247","4,794",...,163,140,550,NaN,"174,417","1,362","180,995",NaN,NaN,0.0

In [4]:
seoul_4th.columns.tolist()

['구시군명',
 'column_0',
 '읍면동명',
 '선거인수',
 'column_3',
 '투표수',
 '           후보자별 득표수_열린우리당\n강금실',
 '한나라당\n오세훈',
 '민주당\n박주선',
 '민주노동당\n김종철',
 '국민중심당\n임웅균',
 '시민당\n이귀선',
 '한미준\n이태희',
 '무소속\n백승원',
 'column_13',
 '계',
 '무효\n투표수',
 '기권수',
 'column_17',
 'column_18',
 'column_19']


## Busan

In [5]:
busan_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/26_부산"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/26_부산
------------------------------------------------------------
폴더에서 16개 파일 발견

처리 중: 2601_중구_부산광역시.xls (지역: 중구)
WARNING *** file size (117881) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2602_서구_부산광역시.xls (지역: 서구)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2603_동구_부산광역시.xls (지역: 동구)
WARNING *** file size (195657) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 27

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 27행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2604_영도구_부산광역시.xls (지역: 영도구)
WARNING *** file size (170804) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2605_부산진구_부산광역시.xls (지역: 부산진구)
WARNING *** file size (263390) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 35

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 35행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2606_동래구_부산광역시.xls (지역: 동래구)
WARNING *** file size (170845) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2607_남구_부산광역시.xls (지역: 남구)
WARNING *** file size (212943) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 29

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 29행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2608_북구_부산광역시.xls (지역: 북구)
WARNING *** file size (162568) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 23

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 23행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2609_해운대구_부산광역시.xls (지역: 해운대구)
WARNING *** file size (204693) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 28

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 28행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2610_기장군_부산광역시.xls (지역: 기장군)
WARNING *** file size (76538) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 7

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 7행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2611_사하구_부산광역시.xls (지역: 사하구)
WARNING *** file size (187546) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 26

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 26행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2612_금정구_부산광역시.xls (지역: 금정구)
WARNING *** file size (204553) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 28

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 28행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2613_강서구_부산광역시.xls (지역: 강서구)
WARNING *** file size (101389) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 10

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 10행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2614_연제구_부산광역시.xls (지역: 연제구)
WARNING *** file size (162498) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 23

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 23행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2615_수영구_부산광역시.xls (지역: 수영구)
WARNING *** file size (126334) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2616_사상구_부산광역시.xls (지역: 사상구)
WARNING *** file size (170848) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 16개 파일
  - 실패: 0개 파일
  - 최종 크기: 16행 x 16열

In [6]:
busan_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n오거돈,한나라당\n허남식,민주노동당\n김석준,column_8,계,무효\n투표수,기권수,column_12,column_13,column_14
0,중구,NaN,합계,"43,062",NaN,"22,768","5,155","15,325","2,047",NaN,"22,527",241,"20,294",NaN,NaN,0.0
1,서구,NaN,합계,"112,683",NaN,"55,046","11,782","37,607","5,038",NaN,"54,427",619,"57,637",NaN,NaN,0.0
2,동구,NaN,합계,"89,864",NaN,"46,773","10,749","30,690","4,592",NaN,"46,031",742,"43,091",NaN,NaN,0.0
3,영도구,NaN,합계,"131,447",NaN,"63,268","17,638","38,017","6,857",NaN,"62,512",756,"68,179",NaN,NaN,0.0
4,부산진구,NaN,합계,"325,963",NaN,"157,499","35,746","103,671","16,643",NaN,"156,060","1,439","168,464",NaN,NaN,0.0
5,동래구,NaN,합계,"216,997",NaN,"107,497","23,133","73,580","10,026",NaN,"106,739",758,"109,500",NaN,NaN,0.0
6,남구,NaN,합계,"238,368",NaN,"116,840","28,203","75,331","12,390",NaN,"115,924",916,"121,528",NaN,NaN,0.0
7,북구,NaN,합계,"248,396",NaN,"117,428","29,620","73,619","13,223",NaN,"116,462",966,"130,968",NaN,NaN,0.0
8,해운대구,NaN,합계,"309,668",NaN,"145,642","35,920","93,928","14,637",NaN,"144,485","1,157","164,026",NaN,NaN,0.0
9,기장군,NaN,합계,"61,953",NaN,"36,135","8,326","23,264","3,995",NaN,"35,585",550,"25,818",NaN,NaN,0.0
10,사하구,NaN,합계,"284,656",NaN,"128,377","33,222","81,442","12,695",NaN,"127,359","1,018","156,279",NaN,NaN,0.0
11,금정구,NaN,합계,"209,276",NaN,"103,941","21,975","68,921","11,996",NaN,"102,892","1,049","105,335",NaN,NaN,0.0
12,강서구,NaN,합계,"44,796",NaN,"26,882","7,855","16,267","2,261",NaN,"26,383",499,"17,914",NaN,NaN,0.0
13,연제구,NaN,합계,"172,349",NaN,"84,791","19,613","55,918","8,557",NaN,"84,088",703,"87,558",NaN,NaN,0.0
14,수영구,NaN,합계,"143,359",NaN,"67,640","15,118","45,774","6,255",NaN,"67,147",493,"75,719",NaN,NaN,0.0
15,사상구,NaN,합계,"212,267",NaN,"98,091","25,415","61,860","9,849",NaN,"97,124",967,"114,176",NaN,NaN,0.0


## Daegu

In [7]:
daegu_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/27_대구"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/27_대구
------------------------------------------------------------
폴더에서 8개 파일 발견

처리 중: 2701_중구_대구광역시.xls (지역: 중구)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 17
데이터 행 수: 23

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 23행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2702_동구_대구광역시.xls (지역: 동구)
WARNING *** file size (139687) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 17
데이터 행 수: 30

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 30행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2703_서구_대구광역시.xls (지역: 서구)
WARNING *** file size (118590) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 17
데이터 행 수: 26

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 26행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2704_남구_대구광역시.xls (지역: 남구)
WARNING *** file size (103070) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 17
데이터 행 수: 23

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 23행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2705_북구_대구광역시.xls (지역: 북구)
WARNING *** file size (160285) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 17
데이터 행 수: 34

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 34행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2706_수성구_대구광역시.xls (지역: 수성구)
WARNING *** file size (155138) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 17
데이터 행 수: 33

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 33행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2707_달서구_대구광역시.xls (지역: 달서구)
WARNING *** file size (160336) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 17
데이터 행 수: 34

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 34행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2708_달성군_대구광역시.xls (지역: 달성군)
WARNING *** file size (70543) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 17
데이터 행 수: 11

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 11행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 8개 파일
  - 실패: 0개 파일
  - 최종 크기: 8행 x 18열

In [8]:
daegu_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n이재용,한나라당\n김범일,민주노동당\n이연재,국민중심당\n박승국,무소속\n백승홍,column_10,계,무효\n투표수,기권수,column_14,column_15,column_16
0,중구,NaN,합계,"66,126",NaN,"35,274","7,753","24,056",960,228,"1,870",NaN,"34,867",407,"30,852",NaN,NaN,0.0
1,동구,NaN,합계,"267,710",NaN,"129,221","27,773","90,128","4,935","1,291","3,714",NaN,"127,841","1,380","138,489",NaN,NaN,0.0
2,서구,NaN,합계,"194,812",NaN,"92,272","16,137","63,241","3,304",807,"7,757",NaN,"91,246","1,026","102,540",NaN,NaN,0.0
3,남구,NaN,합계,"145,954",NaN,"70,026","17,919","47,545","1,876",387,"1,706",NaN,"69,433",593,"75,928",NaN,NaN,0.0
4,북구,NaN,합계,"341,531",NaN,"159,678","32,906","110,959","6,687","2,731","5,025",NaN,"158,308","1,370","181,853",NaN,NaN,0.0
5,수성구,NaN,합계,"320,246",NaN,"157,451","31,146","114,184","5,563","1,090","4,375",NaN,"156,358","1,093","162,795",NaN,NaN,0.0
6,달서구,NaN,합계,"432,607",NaN,"206,965","43,630","145,236","7,956","1,331","7,388",NaN,"205,541","1,424","225,642",NaN,NaN,0.0
7,달성군,NaN,합계,"116,057",NaN,"64,173","13,867","40,708","4,216",899,"3,397",NaN,"63,087","1,086","51,884",NaN,NaN,0.0


## Incheon

In [9]:
incheon_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/28_인천"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/28_인천
------------------------------------------------------------
폴더에서 10개 파일 발견

처리 중: 2801_중구_인천광역시.xls (지역: 중구)
WARNING *** file size (96823) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2802_동구_인천광역시.xls (지역: 동구)
WARNING *** file size (119002) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2803_남구_인천광역시.xls (지역: 남구)
WARNING *** file size (207669) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 34

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 34행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2804_연수구_인천광역시.xls (지역: 연수구)
WARNING *** file size (96960) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2805_남동구_인천광역시.xls (지역: 남동구)
WARNING *** file size (160074) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 27

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 27행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2806_부평구_인천광역시.xls (지역: 부평구)
WARNING *** file size (193793) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 32

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 32행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2807_계양구_인천광역시.xls (지역: 계양구)
WARNING *** file size (119154) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2808_서구_인천광역시.xls (지역: 서구)
WARNING *** file size (153339) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 26

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 26행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2809_강화군_인천광역시.xls (지역: 강화군)
WARNING *** file size (132791) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 23

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 23행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2810_옹진군_인천광역시.xls (지역: 옹진군)
WARNING *** file size (76507) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 9

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 9행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 10개 파일
  - 실패: 0개 파일
  - 최종 크기: 10행 x 17열

In [10]:
incheon_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n최기선,한나라당\n안상수,민주당\n신경철,민주노동당\n김성진,column_9,계,무효\n투표수,기권수,column_13,column_14,column_15
0,중구,NaN,합계,"72,876",NaN,"34,796","8,119","21,570","1,877","2,764",NaN,"34,330",466,"38,080",NaN,NaN,0.0
1,동구,NaN,합계,"61,515",NaN,"30,794","6,663","18,707","1,483","3,514",NaN,"30,367",427,"30,721",NaN,NaN,0.0
2,남구,NaN,합계,"327,614",NaN,"140,581","31,036","90,299","6,402","11,403",NaN,"139,140","1,441","187,033",NaN,NaN,0.0
3,연수구,NaN,합계,"191,076",NaN,"88,010","19,370","57,235","2,892","7,873",NaN,"87,370",640,"103,066",NaN,NaN,0.0
4,남동구,NaN,합계,"284,121",NaN,"123,423","28,961","73,284","7,794","12,285",NaN,"122,324","1,099","160,698",NaN,NaN,0.0
5,부평구,NaN,합계,"425,004",NaN,"181,447","42,156","106,584","11,245","19,942",NaN,"179,927","1,520","243,557",NaN,NaN,0.0
6,계양구,NaN,합계,"239,585",NaN,"100,411","26,480","58,806","5,363","8,963",NaN,"99,612",799,"139,174",NaN,NaN,0.0
7,서구,NaN,합계,"271,645",NaN,"114,473","27,258","70,169","6,074","9,834",NaN,"113,335","1,138","157,172",NaN,NaN,0.0
8,강화군,NaN,합계,"53,699",NaN,"35,405","8,071","23,919",860,"1,700",NaN,"34,550",855,"18,294",NaN,NaN,0.0
9,옹진군,NaN,합계,"13,268",NaN,"10,166","2,536","6,359",349,620,NaN,"9,864",302,"3,102",NaN,NaN,0.0


## Gwangju

In [11]:
gwangju_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/29_광주"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/29_광주
------------------------------------------------------------
폴더에서 5개 파일 발견

처리 중: 2901_동구_광주광역시.xls (지역: 동구)
WARNING *** file size (132977) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 23

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 23행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2902_서구_광주광역시.xls (지역: 서구)
WARNING *** file size (160005) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 27

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 27행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2903_남구_광주광역시.xls (지역: 남구)
WARNING *** file size (153225) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 26

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 26행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2904_북구_광주광역시.xls (지역: 북구)
WARNING *** file size (229899) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 43

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 43행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 2905_광산구_광주광역시.xls (지역: 광산구)
WARNING *** file size (173430) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 29

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 29행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 5개 파일
  - 실패: 0개 파일
  - 최종 크기: 5행 x 17열

In [12]:
gwangju_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n조영택,한나라당\n한영,민주당\n박광태,민주노동당\n오병윤,column_9,계,무효\n투표수,기권수,column_13,column_14,column_15
0,동구,NaN,합계,"90,767",NaN,"43,236","16,085","2,201","21,204","3,240",NaN,"42,730",506,"47,531",NaN,NaN,0.0
1,서구,NaN,합계,"221,034",NaN,"102,566","34,849","3,911","51,556","11,386",NaN,"101,702",864,"118,468",NaN,NaN,0.0
2,남구,NaN,합계,"161,406",NaN,"78,309","26,536","3,011","42,078","5,861",NaN,"77,486",823,"83,097",NaN,NaN,0.0
3,북구,NaN,합계,"333,413",NaN,"147,702","53,265","5,905","72,580","14,636",NaN,"146,386","1,316","185,711",NaN,NaN,0.0
4,광산구,NaN,합계,"208,000",NaN,"97,503","27,021","3,433","52,466","13,494",NaN,"96,414","1,089","110,497",NaN,NaN,0.0


## Daejeon

In [13]:
daejeon_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/30_대전"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/30_대전
------------------------------------------------------------
폴더에서 5개 파일 발견

처리 중: 3001_동구_대전광역시.xls (지역: 동구)
WARNING *** file size (102063) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 18
데이터 행 수: 31

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 31행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 3002_중구_대전광역시.xls (지역: 중구)
WARNING *** file size (84434) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 18
데이터 행 수: 26

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 26행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 3003_서구_대전광역시.xls (지역: 서구)
WARNING *** file size (105913) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 18
데이터 행 수: 32

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 32행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 3004_유성구_대전광역시.xls (지역: 유성구)
WARNING *** file size (46747) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 18
데이터 행 수: 10

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 10행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 3005_대덕구_대전광역시.xls (지역: 대덕구)
WARNING *** file size (70087) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 18
데이터 행 수: 22

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 22행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 5개 파일
  - 실패: 0개 파일
  - 최종 크기: 5행 x 19열

In [14]:
daejeon_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n염홍철,한나라당\n박성효,민주당\n최기복,민주노동당\n박춘호,국민중심당\n남충희,한미준\n고낙정,column_11,계,무효\n투표수,기권수,column_15,column_16,column_17
0,동구,NaN,합계,"183,206",NaN,"87,967","36,078","35,745","1,262","2,401","10,736",685,NaN,"86,907","1,060","95,239",NaN,NaN,0.0
1,중구,NaN,합계,"203,076",NaN,"100,902","39,961","44,780","1,202","2,324","11,290",456,NaN,"100,013",889,"102,174",NaN,NaN,0.0
2,서구,NaN,합계,"367,265",NaN,"182,493","73,194","83,617","2,040","4,025","17,622",759,NaN,"181,257","1,236","184,772",NaN,NaN,0.0
3,유성구,NaN,합계,"164,867",NaN,"84,058","36,081","36,053",873,"2,979","7,204",354,NaN,"83,544",514,"80,809",NaN,NaN,0.0
4,대덕구,NaN,합계,"159,054",NaN,"77,148","31,959","31,294","1,065","3,170","8,379",453,NaN,"76,320",828,"81,906",NaN,NaN,0.0


## Ulsan

In [15]:
ulsan_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/31_울산"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/31_울산
------------------------------------------------------------
폴더에서 5개 파일 발견

처리 중: 3101_중구_울산광역시.xls (지역: 중구)
WARNING *** file size (170774) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 3102_남구_울산광역시.xls (지역: 남구)
WARNING *** file size (170826) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 3103_동구_울산광역시.xls (지역: 동구)
WARNING *** file size (126389) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 3104_북구_울산광역시.xls (지역: 북구)
WARNING *** file size (109724) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 11

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 11행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 3105_울주군_울산광역시.xls (지역: 울주군)
WARNING *** file size (154147) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 22

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 22행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 5개 파일
  - 실패: 0개 파일
  - 최종 크기: 5행 x 16열

In [16]:
ulsan_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n심규명,한나라당\n박맹우,민주노동당\n노옥희,column_8,계,무효\n투표수,기권수,column_12,column_13,column_14
0,중구,NaN,합계,"175,337",NaN,"88,549","9,023","59,499","19,390",NaN,"87,912",637,"86,788",NaN,NaN,0.0
1,남구,NaN,합계,"250,864",NaN,"123,837","14,533","85,037","23,446",NaN,"123,016",821,"127,027",NaN,NaN,0.0
2,동구,NaN,합계,"136,957",NaN,"75,733","8,675","40,077","26,290",NaN,"75,042",691,"61,224",NaN,NaN,0.0
3,북구,NaN,합계,"99,489",NaN,"55,385","5,176","28,677","21,047",NaN,"54,900",485,"44,104",NaN,NaN,0.0
4,울주군,NaN,합계,"127,642",NaN,"73,696","10,172","48,071","14,211",NaN,"72,454","1,242","53,946",NaN,NaN,0.0


## Gyeonggi

In [17]:
gyeonggi_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/41_경기"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/41_경기
------------------------------------------------------------
폴더에서 44개 파일 발견

처리 중: 4101_수원시장안구_경기도.xls (지역: 수원시장안구)
WARNING *** file size (103618) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4102_수원시권선구_경기도.xls (지역: 수원시권선구)
WARNING *** file size (103701) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4103_수원시팔달구_경기도.xls (지역: 수원시팔달구)
WARNING *** file size (125786) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 22

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 22행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4104_수원시영통구_경기도.xls (지역: 수원시영통구)
WARNING *** file size (96879) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4105_성남시수정구_경기도.xls (지역: 성남시수정구)
WARNING *** file size (153259) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 26

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 26행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4106_성남시중원구_경기도.xls (지역: 성남시중원구)
WARNING *** file size (103674) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4107_성남시분당구_경기도.xls (지역: 성남시분당구)
WARNING *** file size (173433) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 29

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 29행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4108_의정부시_경기도.xls (지역: 의정부시)
WARNING *** file size (139910) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4109_안양시만안구_경기도.xls (지역: 안양시만안구)
WARNING *** file size (139818) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4110_안양시동안구_경기도.xls (지역: 안양시동안구)
WARNING *** file size (160052) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 27

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 27행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4111_부천시원미구_경기도.xls (지역: 부천시원미구)
WARNING *** file size (180240) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 30

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 30행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4112_부천시소사구_경기도.xls (지역: 부천시소사구)
WARNING *** file size (103637) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4113_부천시오정구_경기도.xls (지역: 부천시오정구)
WARNING *** file size (83421) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 10

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 10행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4114_광명시_경기도.xls (지역: 광명시)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 28

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 28행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4115_평택시_경기도.xls (지역: 평택시)
WARNING *** file size (193700) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 32

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 32행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4116_양주시_경기도.xls (지역: 양주시)
WARNING *** file size (103619) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4117_동두천시_경기도.xls (지역: 동두천시)
WARNING *** file size (83330) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 10

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 10행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4118_안산시상록구_경기도.xls (지역: 안산시상록구)
WARNING *** file size (125848) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 22

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 22행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4119_안산시단원구_경기도.xls (지역: 안산시단원구)
WARNING *** file size (125826) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 22

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 22행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4120_고양시덕양구_경기도.xls (지역: 고양시덕양구)
WARNING *** file size (173471) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 29

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 29행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4121_고양시일산동구_경기도.xls (지역: 고양시일산동구)
WARNING *** file size (103574) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4122_고양시일산서구_경기도.xls (지역: 고양시일산서구)
WARNING *** file size (96879) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4123_과천시_경기도.xls (지역: 과천시)
WARNING *** file size (76581) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 9

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 9행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4124_의왕시_경기도.xls (지역: 의왕시)
WARNING *** file size (76668) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 9

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 9행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4125_구리시_경기도.xls (지역: 구리시)
WARNING *** file size (90134) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 11

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 11행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4126_남양주시_경기도.xls (지역: 남양주시)
WARNING *** file size (146615) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 25

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 25행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4127_오산시_경기도.xls (지역: 오산시)
WARNING *** file size (76636) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 9

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 9행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4128_화성시_경기도.xls (지역: 화성시)
WARNING *** file size (180114) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 30

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 30행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4129_시흥시_경기도.xls (지역: 시흥시)
WARNING *** file size (139824) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4130_군포시_경기도.xls (지역: 군포시)
WARNING *** file size (119131) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4131_하남시_경기도.xls (지역: 하남시)
WARNING *** file size (103558) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4132_파주시_경기도.xls (지역: 파주시)
WARNING *** file size (139707) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4133_여주군_경기도.xls (지역: 여주군)
WARNING *** file size (103526) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4134_이천시_경기도.xls (지역: 이천시)
WARNING *** file size (139745) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4135_용인시처인구_경기도.xls (지역: 용인시처인구)
WARNING *** file size (119061) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4136_용인시수지구_경기도.xls (지역: 용인시수지구)
WARNING *** file size (96910) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4137_용인시기흥구_경기도.xls (지역: 용인시기흥구)
WARNING *** file size (96869) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4138_안성시_경기도.xls (지역: 안성시)
WARNING *** file size (146394) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 25

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 25행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4139_김포시_경기도.xls (지역: 김포시)
WARNING *** file size (103584) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4140_광주시_경기도.xls (지역: 광주시)
WARNING *** file size (103564) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4141_포천시_경기도.xls (지역: 포천시)
WARNING *** file size (139696) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4142_연천군_경기도.xls (지역: 연천군)
WARNING *** file size (96695) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4143_양평군_경기도.xls (지역: 양평군)
WARNING *** file size (119053) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4144_가평군_경기도.xls (지역: 가평군)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 9

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 9행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 44개 파일
  - 실패: 0개 파일
  - 최종 크기: 44행 x 17열

In [18]:
gyeonggi_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n진대제,한나라당\n김문수,민주당\n박정일,민주노동당\n김용한,column_9,계,무효\n투표수,기권수,column_13,column_14,column_15
0,수원시장안구,NaN,합계,"206,015",NaN,"98,094","31,861","56,361","3,366","5,795",NaN,"97,383",711,"107,921",NaN,NaN,0.0
1,수원시권선구,NaN,합계,"217,455",NaN,"97,485","31,707","56,267","2,822","5,838",NaN,"96,634",851,"119,970",NaN,NaN,0.0
2,수원시팔달구,NaN,합계,"166,662",NaN,"72,030","22,480","42,829","2,501","3,520",NaN,"71,330",700,"94,632",NaN,NaN,0.0
3,수원시영통구,NaN,합계,"173,454",NaN,"82,006","31,247","45,246","1,653","3,442",NaN,"81,588",418,"91,448",NaN,NaN,0.0
4,성남시수정구,NaN,합계,"206,678",NaN,"84,853","28,638","41,683","7,413","6,071",NaN,"83,805","1,048","121,825",NaN,NaN,0.0
5,성남시중원구,NaN,합계,"207,205",NaN,"82,650","26,147","41,203","7,825","6,653",NaN,"81,828",822,"124,555",NaN,NaN,0.0
6,성남시분당구,NaN,합계,"330,404",NaN,"164,190","46,797","107,353","4,380","4,789",NaN,"163,319",871,"166,214",NaN,NaN,0.0
7,의정부시,NaN,합계,"299,556",NaN,"130,381","41,367","77,107","3,905","6,738",NaN,"129,117","1,264","169,175",NaN,NaN,0.0
8,안양시만안구,NaN,합계,"204,688",NaN,"95,595","31,436","53,699","4,500","5,055",NaN,"94,690",905,"109,093",NaN,NaN,0.0
9,안양시동안구,NaN,합계,"259,321",NaN,"134,635","46,671","76,522","4,696","5,789",NaN,"133,678",957,"124,686",NaN,NaN,0.0
10,부천시원미구,NaN,합계,"327,003",NaN,"143,407","41,878","88,972","5,266","6,140",NaN,"142,256","1,151","183,596",NaN,NaN,0.0
11,부천시소사구,NaN,합계,"170,625",NaN,"78,660","17,302","55,269","2,615","2,808",NaN,"77,994",666,"91,965",NaN,NaN,0.0
12,부천시오정구,NaN,합계,"137,195",NaN,"53,681","15,818","30,607","3,972","2,622",NaN,"53,019",662,"83,514",NaN,NaN,0.0
13,광명시,NaN,합계,"239,187",NaN,"112,843","36,497","61,192","7,718","6,376",NaN,"111,783","1,060","126,344",NaN,NaN,0.0
14,평택시,NaN,합계,"284,458",NaN,"139,667","37,584","78,709","4,384","16,756",NaN,"137,433","2,234","144,791",NaN,NaN,0.0
15,양주시,NaN,합계,"121,097",NaN,"61,143","17,730","36,566","2,684","3,082",NaN,"60,062","1,081","59,954",NaN,NaN,0.0
16,동두천시,NaN,합계,"63,655",NaN,"33,131","10,518","19,435","1,050","1,519",NaN,"32,522",609,"30,524",NaN,NaN,0.0
17,안산시상록구,NaN,합계,"253,921",NaN,"102,640","33,799","54,662","5,849","7,431",NaN,"101,741",899,"151,281",NaN,NaN,0.0
18,안산시단원구,NaN,합계,"230,496",NaN,"94,613","29,832","51,198","5,398","7,333",NaN,"93,761",852,"135,883",NaN,NaN,0.0
19,고양시덕양구,NaN,합계,"287,230",NaN,"130,051","40,606","76,495","5,674","6,182",NaN,"128,957","1,094","157,179",NaN,NaN,0.0
20,고양시일산동구,NaN,합계,"162,750",NaN,"73,926","23,061","45,372","2,113","2,903",NaN,"73,449",477,"88,824",NaN,NaN,0.0
21,고양시일산서구,NaN,합계,"201,819",NaN,"95,298","30,561","57,838","2,685","3,590",NaN,"94,674",624,"106,521",NaN,NaN,0.0
22,과천시,NaN,합계,"43,524",NaN,"25,790","8,309","15,453",617,"1,176",NaN,"25,555",235,"17,734",NaN,NaN,0.0
23,의왕시,NaN,합계,"105,917",NaN,"53,783","17,693","30,792","2,207","2,621",NaN,"53,313",470,"52,134",NaN,NaN,0.0
24,구리시,NaN,합계,"140,385",NaN,"68,671","22,085","40,106","2,622","3,232",NaN,"68,045",626,"71,714",NaN,NaN,0.0
25,남양주시,NaN,합계,"336,528",NaN,"148,529","42,065","89,434","6,389","8,795",NaN,"146,683","1,846","187,999",NaN,NaN,0.0
26,오산시,NaN,합계,"94,380",NaN,"45,858","14,852","25,582","1,892","2,956",NaN,"45,282",576,"48,522",NaN,NaN,0.0
27,화성시,NaN,합계,"223,162",NaN,"100,402","28,894","59,794","2,915","7,550",NaN,"99,153","1,249","122,760",NaN,NaN,0.0
28,시흥시,NaN,합계,"271,413",NaN,"109,489","34,414","61,397","6,123","6,487",NaN,"108,421","1,068","161,924",NaN,NaN,0.0
29,군포시,NaN,합계,"203,276",NaN,"103,793","36,202","57,058","4,155","5,548",NaN,"102,963",830,"99,483",NaN,NaN,0.0
30,하남시,NaN,합계,"103,677",NaN,"52,387","14,718","31,652","2,553","2,796",NaN,"51,719",668,"51,290",NaN,NaN,0.0
31,파주시,NaN,합계,"206,376",NaN,"98,474","26,039","63,372","2,775","4,608",NaN,"96,794","1,680","107,902",NaN,NaN,0.0
32,여주군,NaN,합계,"79,881",NaN,"41,534","10,587","26,199","1,230","2,605",NaN,"40,621",913,"38,347",NaN,NaN,0.0
33,이천시,NaN,합계,"140,754",NaN,"66,688","18,038","41,377","2,548","3,648",NaN,"65,611","1,077","74,066",NaN,NaN,0.0
34,용인시처인구,NaN,합계,"146,083",NaN,"67,523","20,302","40,745","2,135","3,274",NaN,"66,456","1,067","78,560",NaN,NaN,0.0
35,용인시수지구,NaN,합계,"196,871",NaN,"97,153","28,927","63,260","1,800","2,690",NaN,"96,677",476,"99,718",NaN,NaN,0.0
36,용인시기흥구,NaN,합계,"175,478",NaN,"84,664","27,293","51,321","2,155","3,258",NaN,"84,027",637,"90,814",NaN,NaN,0.0
37,안성시,NaN,합계,"119,170",NaN,"64,428","19,349","36,415","1,663","5,865",NaN,"63,292","1,136","54,742",NaN,NaN,0.0
38,김포시,NaN,합계,"152,704",NaN,"77,104","21,661","48,646","2,766","3,016",NaN,"76,089","1,015","75,600",NaN,NaN,0.0
39,광주시,NaN,합계,"161,569",NaN,"73,070","20,354","45,080","3,888","2,889",NaN,"72,211",859,"88,499",NaN,NaN,0.0
40,포천시,NaN,합계,"117,916",NaN,"59,905","15,958","37,858","1,983","2,883",NaN,"58,682","1,223","58,011",NaN,NaN,0.0
41,연천군,NaN,합계,"36,970",NaN,"22,966","6,489","13,683","1,056","1,134",NaN,"22,362",604,"14,004",NaN,NaN,0.0
42,양평군,NaN,합계,"68,290",NaN,"42,689","9,225","28,979","1,434","2,113",NaN,"41,751",938,"25,601",NaN,NaN,0.0
43,가평군,NaN,합계,"43,630",NaN,"29,673","7,326","18,889","1,034","1,530",NaN,"28,779",894,"13,957",NaN,NaN,0.0


## Gangwon

In [19]:
gangwon_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/42_강원"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/42_강원
------------------------------------------------------------
폴더에서 18개 파일 발견

처리 중: 4201_춘천시_강원도.xls (지역: 춘천시)
WARNING *** file size (214280) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 35

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 35행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4202_원주시_강원도.xls (지역: 원주시)
WARNING *** file size (207438) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 34

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 34행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4203_강릉시_강원도.xls (지역: 강릉시)
WARNING *** file size (186652) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 31

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 31행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4204_동해시_강원도.xls (지역: 동해시)
WARNING *** file size (96782) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4205_삼척시_강원도.xls (지역: 삼척시)
WARNING *** file size (118910) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4206_태백시_강원도.xls (지역: 태백시)
WARNING *** file size (90014) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 11

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 11행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4207_정선군_강원도.xls (지역: 정선군)
WARNING *** file size (96678) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4208_속초시_강원도.xls (지역: 속초시)
WARNING *** file size (90003) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 11

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 11행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4209_고성군_강원도.xls (지역: 고성군)
WARNING *** file size (62631) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 7

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 7행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4210_양양군_강원도.xls (지역: 양양군)
WARNING *** file size (76491) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 9

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 9행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4211_인제군_강원도.xls (지역: 인제군)
WARNING *** file size (76511) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 9

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 9행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4212_홍천군_강원도.xls (지역: 홍천군)
WARNING *** file size (103447) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4213_횡성군_강원도.xls (지역: 횡성군)
WARNING *** file size (96684) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4214_영월군_강원도.xls (지역: 영월군)
WARNING *** file size (89944) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 11

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 11행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4215_평창군_강원도.xls (지역: 평창군)
WARNING *** file size (89968) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 11

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 11행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4216_화천군_강원도.xls (지역: 화천군)
WARNING *** file size (62642) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 7

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 7행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4217_양구군_강원도.xls (지역: 양구군)
WARNING *** file size (62591) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 7

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 7행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4218_철원군_강원도.xls (지역: 철원군)
WARNING *** file size (83212) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 10

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 10행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 18개 파일
  - 실패: 0개 파일
  - 최종 크기: 18행 x 17열

In [20]:
gangwon_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n이창복,한나라당\n김진선,민주당\n유재규,국민중심당\n유승규,column_9,계,무효\n투표수,기권수,column_13,column_14,column_15
0,춘천시,NaN,합계,"192,644",NaN,"104,177","36,231","45,125","11,660","7,673",NaN,"100,689","3,488","88,467",NaN,NaN,0.0
1,원주시,NaN,합계,"215,770",NaN,"106,902","31,345","70,598","2,397","1,321",NaN,"105,661","1,241","108,868",NaN,NaN,0.0
2,강릉시,NaN,합계,"171,138",NaN,"92,512","12,467","74,805","2,064","1,709",NaN,"91,045","1,467","78,626",NaN,NaN,0.0
3,동해시,NaN,합계,"74,884",NaN,"43,269","4,903","36,395",803,586,NaN,"42,687",582,"31,615",NaN,NaN,0.0
4,삼척시,NaN,합계,"57,751",NaN,"39,784","4,897","31,894",993,"1,174",NaN,"38,958",826,"17,967",NaN,NaN,0.0
5,태백시,NaN,합계,"41,345",NaN,"27,807","4,148","21,005",464,"1,781",NaN,"27,398",409,"13,538",NaN,NaN,0.0
6,정선군,NaN,합계,"35,948",NaN,"25,156","4,982","18,270",715,697,NaN,"24,664",492,"10,792",NaN,NaN,0.0
7,속초시,NaN,합계,"64,750",NaN,"34,125","6,072","26,288",826,471,NaN,"33,657",468,"30,625",NaN,NaN,0.0
8,고성군,NaN,합계,"25,708",NaN,"18,721","3,010","14,514",493,299,NaN,"18,316",405,"6,987",NaN,NaN,0.0
9,양양군,NaN,합계,"23,582",NaN,"16,899","2,584","13,324",415,240,NaN,"16,563",336,"6,683",NaN,NaN,0.0
10,인제군,NaN,합계,"25,130",NaN,"18,235","4,059","12,913",508,320,NaN,"17,800",435,"6,895",NaN,NaN,0.0
11,홍천군,NaN,합계,"55,429",NaN,"33,777","7,711","22,544","2,041",770,NaN,"33,066",711,"21,652",NaN,NaN,0.0
12,횡성군,NaN,합계,"35,200",NaN,"24,116","4,919","15,734","2,548",433,NaN,"23,634",482,"11,084",NaN,NaN,0.0
13,영월군,NaN,합계,"33,449",NaN,"22,727","4,950","16,488",554,357,NaN,"22,349",378,"10,722",NaN,NaN,0.0
14,평창군,NaN,합계,"36,045",NaN,"23,370","5,629","16,346",538,464,NaN,"22,977",393,"12,675",NaN,NaN,0.0
15,화천군,NaN,합계,"18,404",NaN,"13,079","2,908","8,852",610,354,NaN,"12,724",355,"5,325",NaN,NaN,0.0
16,양구군,NaN,합계,"16,454",NaN,"12,044","2,545","8,379",497,319,NaN,"11,740",304,"4,410",NaN,NaN,0.0
17,철원군,NaN,합계,"37,346",NaN,"24,933","4,942","18,139",902,415,NaN,"24,398",535,"12,413",NaN,NaN,0.0


## Chungbuk

In [21]:
chungbuk_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/43_충북"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/43_충북
------------------------------------------------------------
폴더에서 13개 파일 발견

처리 중: 4301_청주시상당구_충청북도.xls (지역: 청주시상당구)
WARNING *** file size (133126) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 23

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 23행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4302_청주시흥덕구_충청북도.xls (지역: 청주시흥덕구)
WARNING *** file size (153358) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 26

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 26행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4303_충주시_충청북도.xls (지역: 충주시)
WARNING *** file size (214188) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 35

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 35행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4304_제천시_충청북도.xls (지역: 제천시)
WARNING *** file size (159864) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 27

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 27행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4305_단양군_충청북도.xls (지역: 단양군)
WARNING *** file size (83308) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 10

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 10행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4306_청원군_충청북도.xls (지역: 청원군)
WARNING *** file size (139677) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4307_영동군_충청북도.xls (지역: 영동군)
WARNING *** file size (103490) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4308_보은군_충청북도.xls (지역: 보은군)
WARNING *** file size (118809) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4309_옥천군_충청북도.xls (지역: 옥천군)
WARNING *** file size (96733) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4310_음성군_충청북도.xls (지역: 음성군)
WARNING *** file size (96769) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4311_진천군_충청북도.xls (지역: 진천군)
WARNING *** file size (83279) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 10

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 10행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4312_괴산군_충청북도.xls (지역: 괴산군)
WARNING *** file size (118853) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4313_증평군_충청북도.xls (지역: 증평군)
WARNING *** file size (49124) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 5

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 5행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 13개 파일
  - 실패: 0개 파일
  - 최종 크기: 13행 x 17열

In [22]:
chungbuk_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n한범덕,한나라당\n정우택,민주노동당\n배창호,국민중심당\n조병세,column_9,계,무효\n투표수,기권수,column_13,column_14,column_15
0,청주시상당구,NaN,합계,"188,493",NaN,"89,032","28,260","52,776","5,015","2,114",NaN,"88,165",867,"99,461",NaN,NaN,0.0
1,청주시흥덕구,NaN,합계,"269,249",NaN,"121,820","38,846","70,472","8,623","2,740",NaN,"120,681","1,139","147,429",NaN,NaN,0.0
2,충주시,NaN,합계,"155,769",NaN,"83,466","24,287","50,932","4,746","2,095",NaN,"82,060","1,406","72,303",NaN,NaN,0.0
3,제천시,NaN,합계,"105,920",NaN,"60,200","16,169","37,174","3,981","1,845",NaN,"59,169","1,031","45,720",NaN,NaN,0.0
4,단양군,NaN,합계,"27,458",NaN,"19,533","5,643","11,497",994,883,NaN,"19,017",516,"7,925",NaN,NaN,0.0
5,청원군,NaN,합계,"95,259",NaN,"53,191","18,015","27,833","3,274","2,962",NaN,"52,084","1,107","42,068",NaN,NaN,0.0
6,영동군,NaN,합계,"41,700",NaN,"29,569","9,031","15,383","2,646","1,708",NaN,"28,768",801,"12,131",NaN,NaN,0.0
7,보은군,NaN,합계,"30,273",NaN,"22,890","8,833","11,107","1,282","1,078",NaN,"22,300",590,"7,383",NaN,NaN,0.0
8,옥천군,NaN,합계,"44,454",NaN,"31,353","11,522","15,423","2,014","1,362",NaN,"30,321","1,032","13,101",NaN,NaN,0.0
9,음성군,NaN,합계,"66,010",NaN,"38,457","8,678","25,794","2,299","1,030",NaN,"37,801",656,"27,553",NaN,NaN,0.0
10,진천군,NaN,합계,"46,069",NaN,"28,091","5,582","20,081","1,504",428,NaN,"27,595",496,"17,978",NaN,NaN,0.0
11,괴산군,NaN,합계,"32,511",NaN,"23,933","7,471","12,584","2,052","1,027",NaN,"23,134",799,"8,578",NaN,NaN,0.0
12,증평군,NaN,합계,"23,117",NaN,"14,518","3,089","10,101",665,374,NaN,"14,229",289,"8,599",NaN,NaN,0.0


## Chungnam

In [23]:
chungnam_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/44_충남"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/44_충남
------------------------------------------------------------
폴더에서 16개 파일 발견

처리 중: 4401_천안시_충청남도.xls (지역: 천안시)
WARNING *** file size (236691) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 44

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 44행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4402_공주시_충청남도.xls (지역: 공주시)
WARNING *** file size (159887) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 27

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 27행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4403_보령시_충청남도.xls (지역: 보령시)
WARNING *** file size (153166) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 26

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 26행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4404_아산시_충청남도.xls (지역: 아산시)
WARNING *** file size (153328) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 26

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 26행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4405_서산시_충청남도.xls (지역: 서산시)
WARNING *** file size (139831) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4406_태안군_충청남도.xls (지역: 태안군)
WARNING *** file size (83388) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 10

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 10행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4407_금산군_충청남도.xls (지역: 금산군)
WARNING *** file size (96792) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4408_연기군_충청남도.xls (지역: 연기군)
WARNING *** file size (90099) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 11

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 11행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4409_논산시_충청남도.xls (지역: 논산시)
WARNING *** file size (146437) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 25

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 25행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4410_계룡시_충청남도.xls (지역: 계룡시)
WARNING *** file size (55944) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 6

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 6행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4411_부여군_충청남도.xls (지역: 부여군)
WARNING *** file size (146377) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 25

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 25행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4412_서천군_충청남도.xls (지역: 서천군)
WARNING *** file size (125708) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 22

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 22행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4413_홍성군_충청남도.xls (지역: 홍성군)
WARNING *** file size (118963) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4414_청양군_충청남도.xls (지역: 청양군)
WARNING *** file size (103415) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4415_예산군_충청남도.xls (지역: 예산군)
WARNING *** file size (125700) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 22

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 22행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4416_당진군_충청남도.xls (지역: 당진군)
WARNING *** file size (125814) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 22

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 22행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 16개 파일
  - 실패: 0개 파일
  - 최종 크기: 16행 x 17열

In [24]:
chungnam_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n오영교,한나라당\n이완구,민주노동당\n이용길,국민중심당\n이명수,column_9,계,무효\n투표수,기권수,column_13,column_14,column_15
0,천안시,NaN,합계,"372,195",NaN,"162,726","36,426","84,436","15,778","24,136",NaN,"160,776","1,950","209,469",NaN,NaN,0.0
1,공주시,NaN,합계,"100,960",NaN,"61,082","13,868","21,948","3,101","20,682",NaN,"59,599","1,483","39,878",NaN,NaN,0.0
2,보령시,NaN,합계,"84,236",NaN,"52,539","16,826","20,818","2,392","11,282",NaN,"51,318","1,221","31,697",NaN,NaN,0.0
3,아산시,NaN,합계,"156,817",NaN,"74,771","10,839","28,561","6,590","27,467",NaN,"73,457","1,314","82,046",NaN,NaN,0.0
4,서산시,NaN,합계,"112,204",NaN,"61,310","13,144","27,317","3,995","15,341",NaN,"59,797","1,513","50,894",NaN,NaN,0.0
5,태안군,NaN,합계,"51,770",NaN,"35,084","7,572","13,756","1,814","10,701",NaN,"33,843","1,241","16,686",NaN,NaN,0.0
6,금산군,NaN,합계,"47,627",NaN,"32,263","6,017","12,045","1,531","11,653",NaN,"31,246","1,017","15,364",NaN,NaN,0.0
7,연기군,NaN,합계,"65,548",NaN,"39,859","13,698","12,927","1,777","10,431",NaN,"38,833","1,026","25,689",NaN,NaN,0.0
8,논산시,NaN,합계,"104,305",NaN,"57,835","13,044","20,497","2,926","19,699",NaN,"56,166","1,669","46,470",NaN,NaN,0.0
9,계룡시,NaN,합계,"24,442",NaN,"15,359","3,526","7,846",561,"3,209",NaN,"15,142",217,"9,083",NaN,NaN,0.0
10,부여군,NaN,합계,"65,087",NaN,"41,906","7,353","17,686","2,719","12,723",NaN,"40,481","1,425","23,181",NaN,NaN,0.0
11,서천군,NaN,합계,"52,107",NaN,"37,472","10,418","13,363","1,883","10,451",NaN,"36,115","1,357","14,635",NaN,NaN,0.0
12,홍성군,NaN,합계,"71,168",NaN,"44,369","5,122","31,578","1,247","5,602",NaN,"43,549",820,"26,799",NaN,NaN,0.0
13,청양군,NaN,합계,"28,517",NaN,"21,475","2,568","12,875",839,"4,629",NaN,"20,911",564,"7,042",NaN,NaN,0.0
14,예산군,NaN,합계,"72,864",NaN,"44,393","5,762","28,804","1,709","7,186",NaN,"43,461",932,"28,471",NaN,NaN,0.0
15,당진군,NaN,합계,"93,393",NaN,"56,019","11,986","24,963","3,555","14,062",NaN,"54,566","1,453","37,374",NaN,NaN,0.0


## Jeonbuk

In [25]:
jeonbuk_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/45_전북"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/45_전북
------------------------------------------------------------
폴더에서 15개 파일 발견

처리 중: 4501_전주시완산구_전라북도.xls (지역: 전주시완산구)
WARNING *** file size (166803) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 28

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 28행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4502_전주시덕진구_전라북도.xls (지역: 전주시덕진구)
WARNING *** file size (146565) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 25

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 25행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4503_군산시_전라북도.xls (지역: 군산시)
WARNING *** file size (256697) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 47

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 47행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4505_익산시_전라북도.xls (지역: 익산시)
WARNING *** file size (249933) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 46

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 46행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4507_정읍시_전라북도.xls (지역: 정읍시)
WARNING *** file size (200699) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 33

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 33행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4508_남원시_전라북도.xls (지역: 남원시)
WARNING *** file size (200543) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 33

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 33행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4509_김제시_전라북도.xls (지역: 김제시)
WARNING *** file size (173240) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 29

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 29행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4510_완주군_전라북도.xls (지역: 완주군)
WARNING *** file size (125761) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 22

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 22행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4511_진안군_전라북도.xls (지역: 진안군)
WARNING *** file size (118820) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4512_무주군_전라북도.xls (지역: 무주군)
WARNING *** file size (69863) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 8

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 8행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4513_장수군_전라북도.xls (지역: 장수군)
WARNING *** file size (83225) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 10

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 10행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4514_임실군_전라북도.xls (지역: 임실군)
WARNING *** file size (125569) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 22

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 22행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4515_순창군_전라북도.xls (지역: 순창군)
WARNING *** file size (118862) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4516_고창군_전라북도.xls (지역: 고창군)
WARNING *** file size (139577) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4517_부안군_전라북도.xls (지역: 부안군)
WARNING *** file size (125717) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 22

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 22행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 15개 파일
  - 실패: 0개 파일
  - 최종 크기: 15행 x 17열

In [26]:
jeonbuk_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n김완주,한나라당\n문용주,민주당\n정균환,민주노동당\n염경석,column_9,계,무효\n투표수,기권수,column_13,column_14,column_15
0,전주시완산구,NaN,합계,"252,082",NaN,"121,291","59,401","6,322","45,973","8,406",NaN,"120,102","1,189","130,791",NaN,NaN,0.0
1,전주시덕진구,NaN,합계,"198,612",NaN,"94,137","45,562","5,075","34,130","8,560",NaN,"93,327",810,"104,475",NaN,NaN,0.0
2,군산시,NaN,합계,"198,467",NaN,"111,760","44,385","19,593","36,122","9,086",NaN,"109,186","2,574","86,707",NaN,NaN,0.0
3,익산시,NaN,합계,"235,847",NaN,"123,052","55,008","8,189","48,019","9,442",NaN,"120,658","2,394","112,795",NaN,NaN,0.0
4,정읍시,NaN,합계,"99,727",NaN,"62,082","30,801","3,181","21,387","5,254",NaN,"60,623","1,459","37,645",NaN,NaN,0.0
5,남원시,NaN,합계,"72,197",NaN,"50,215","27,923","2,944","15,868","2,271",NaN,"49,006","1,209","21,982",NaN,NaN,0.0
6,김제시,NaN,합계,"82,928",NaN,"55,599","27,773","3,576","19,322","3,272",NaN,"53,943","1,656","27,329",NaN,NaN,0.0
7,완주군,NaN,합계,"66,720",NaN,"41,559","19,070","2,019","15,435","4,089",NaN,"40,613",946,"25,161",NaN,NaN,0.0
8,진안군,NaN,합계,"23,432",NaN,"17,528","9,415","1,437","4,987","1,186",NaN,"17,025",503,"5,904",NaN,NaN,0.0
9,무주군,NaN,합계,"21,301",NaN,"16,835","8,558","1,622","4,857","1,203",NaN,"16,240",595,"4,466",NaN,NaN,0.0
10,장수군,NaN,합계,"20,567",NaN,"16,461","8,836","1,133","4,460","1,478",NaN,"15,907",554,"4,106",NaN,NaN,0.0
11,임실군,NaN,합계,"27,747",NaN,"21,428","10,937","1,509","7,120","1,310",NaN,"20,876",552,"6,319",NaN,NaN,0.0
12,순창군,NaN,합계,"25,579",NaN,"19,723","11,367","1,527","4,723","1,462",NaN,"19,079",644,"5,856",NaN,NaN,0.0
13,고창군,NaN,합계,"51,732",NaN,"37,858","15,802","1,932","16,966","2,156",NaN,"36,856","1,002","13,874",NaN,NaN,0.0
14,부안군,NaN,합계,"52,694",NaN,"37,859","14,598","2,863","16,522","2,497",NaN,"36,480","1,379","14,835",NaN,NaN,0.0


## Jeonnam

In [27]:
jeonnam_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/46_전남"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/46_전남
------------------------------------------------------------
폴더에서 22개 파일 발견

처리 중: 4601_목포시_전라남도.xls (지역: 목포시)
WARNING *** file size (214218) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 35

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 35행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4602_여수시_전라남도.xls (지역: 여수시)
WARNING *** file size (236494) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 44

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 44행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4604_순천시_전라남도.xls (지역: 순천시)
WARNING *** file size (207500) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 34

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 34행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4606_나주시_전라남도.xls (지역: 나주시)
WARNING *** file size (166596) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 28

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 28행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4607_광양시_전라남도.xls (지역: 광양시)
WARNING *** file size (119040) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4608_담양군_전라남도.xls (지역: 담양군)
WARNING *** file size (118936) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4609_장성군_전라남도.xls (지역: 장성군)
WARNING *** file size (118914) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4610_곡성군_전라남도.xls (지역: 곡성군)
WARNING *** file size (103451) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4611_구례군_전라남도.xls (지역: 구례군)
WARNING *** file size (83311) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 10

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 10행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4612_고흥군_전라남도.xls (지역: 고흥군)
WARNING *** file size (153039) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 26

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 26행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4613_보성군_전라남도.xls (지역: 보성군)
WARNING *** file size (125638) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 22

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 22행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4614_화순군_전라남도.xls (지역: 화순군)
WARNING *** file size (132815) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 23

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 23행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4615_장흥군_전라남도.xls (지역: 장흥군)
WARNING *** file size (96761) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4616_강진군_전라남도.xls (지역: 강진군)
WARNING *** file size (118871) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4617_완도군_전라남도.xls (지역: 완도군)
WARNING *** file size (118935) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4618_해남군_전라남도.xls (지역: 해남군)
WARNING *** file size (139664) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4619_진도군_전라남도.xls (지역: 진도군)
WARNING *** file size (83301) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 10

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 10행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4620_영암군_전라남도.xls (지역: 영암군)
WARNING *** file size (118916) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4621_무안군_전라남도.xls (지역: 무안군)
WARNING *** file size (96770) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4622_영광군_전라남도.xls (지역: 영광군)
WARNING *** file size (118920) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4623_함평군_전라남도.xls (지역: 함평군)
WARNING *** file size (90033) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 11

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 11행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4624_신안군_전라남도.xls (지역: 신안군)
WARNING *** file size (132902) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 23

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 23행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 22개 파일
  - 실패: 0개 파일
  - 최종 크기: 22행 x 17열

In [28]:
jeonnam_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n서범석,한나라당\n박재순,민주당\n박준영,민주노동당\n박웅두,column_9,계,무효\n투표수,기권수,column_13,column_14,column_15
0,목포시,NaN,합계,"176,932",NaN,"88,358","12,717","2,667","66,179","5,513",NaN,"87,076","1,282","88,574",NaN,NaN,0.0
1,여수시,NaN,합계,"224,001",NaN,"122,812","32,665","4,973","76,454","6,702",NaN,"120,794","2,018","101,189",NaN,NaN,0.0
2,순천시,NaN,합계,"194,227",NaN,"105,389","27,461","4,311","63,894","7,802",NaN,"103,468","1,921","88,838",NaN,NaN,0.0
3,나주시,NaN,합계,"79,340",NaN,"55,195","5,955","2,484","40,865","4,087",NaN,"53,391","1,804","24,145",NaN,NaN,0.0
4,광양시,NaN,합계,"96,951",NaN,"58,745","20,925","4,266","27,503","5,136",NaN,"57,830",915,"38,206",NaN,NaN,0.0
5,담양군,NaN,합계,"41,974",NaN,"29,475","5,756","1,643","19,625","1,621",NaN,"28,645",830,"12,499",NaN,NaN,0.0
6,장성군,NaN,합계,"39,626",NaN,"27,752","3,757","1,948","19,383","1,938",NaN,"27,026",726,"11,874",NaN,NaN,0.0
7,곡성군,NaN,합계,"28,138",NaN,"21,815","4,152","1,439","12,768","2,730",NaN,"21,089",726,"6,323",NaN,NaN,0.0
8,구례군,NaN,합계,"24,281",NaN,"19,123","4,412","1,118","11,643","1,396",NaN,"18,569",554,"5,158",NaN,NaN,0.0
9,고흥군,NaN,합계,"69,751",NaN,"52,672","8,994","2,733","36,221","2,755",NaN,"50,703","1,969","17,079",NaN,NaN,0.0
10,보성군,NaN,합계,"44,024",NaN,"33,388","3,228","6,864","19,877","2,243",NaN,"32,212","1,176","10,636",NaN,NaN,0.0
11,화순군,NaN,합계,"56,833",NaN,"39,821","4,273","2,542","28,267","3,720",NaN,"38,802","1,019","17,012",NaN,NaN,0.0
12,장흥군,NaN,합계,"36,549",NaN,"27,016","2,911","1,671","18,806","2,807",NaN,"26,195",821,"9,533",NaN,NaN,0.0
13,강진군,NaN,합계,"34,405",NaN,"24,112","3,464","3,247","15,143","1,438",NaN,"23,292",820,"10,293",NaN,NaN,0.0
14,완도군,NaN,합계,"47,793",NaN,"35,481","6,858","1,401","24,688","1,322",NaN,"34,269","1,212","12,312",NaN,NaN,0.0
15,해남군,NaN,합계,"68,768",NaN,"50,577","5,673","2,357","36,921","3,593",NaN,"48,544","2,033","18,191",NaN,NaN,0.0
16,진도군,NaN,합계,"29,821",NaN,"22,635","3,159","1,399","13,372","3,769",NaN,"21,699",936,"7,186",NaN,NaN,0.0
17,영암군,NaN,합계,"48,203",NaN,"32,079","4,670","1,317","23,174","2,078",NaN,"31,239",840,"16,124",NaN,NaN,0.0
18,무안군,NaN,합계,"50,427",NaN,"36,614","8,906","1,287","23,714","1,654",NaN,"35,561","1,053","13,813",NaN,NaN,0.0
19,영광군,NaN,합계,"48,577",NaN,"36,302","5,885","2,698","23,017","2,651",NaN,"34,251","2,051","12,275",NaN,NaN,0.0
20,함평군,NaN,합계,"33,051",NaN,"24,381","3,095","1,374","17,197","1,884",NaN,"23,550",831,"8,670",NaN,NaN,0.0
21,신안군,NaN,합계,"40,240",NaN,"30,078","2,840","1,705","22,183","1,863",NaN,"28,591","1,487","10,162",NaN,NaN,0.0


## Gyeongbuk

In [29]:
gyeongbuk_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/47_경북"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/47_경북
------------------------------------------------------------
폴더에서 24개 파일 발견

처리 중: 4701_포항시북구_경상북도.xls (지역: 포항시북구)
WARNING *** file size (231966) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 27

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 27행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4702_포항시남구_경상북도.xls (지역: 포항시남구)
WARNING *** file size (222131) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 26

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 26행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4703_울릉군_경상북도.xls (지역: 울릉군)
WARNING *** file size (70000) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 5

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 5행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4704_경주시_경상북도.xls (지역: 경주시)
WARNING *** file size (311642) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 35

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 35행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4705_김천시_경상북도.xls (지역: 김천시)
WARNING *** file size (281794) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 32

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 32행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4706_안동시_경상북도.xls (지역: 안동시)
WARNING *** file size (301626) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 34

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 34행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4707_구미시_경상북도.xls (지역: 구미시)
WARNING *** file size (344472) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 44

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 44행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4708_영주시_경상북도.xls (지역: 영주시)
WARNING *** file size (241802) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 28

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 28행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4709_영천시_경상북도.xls (지역: 영천시)
WARNING *** file size (212155) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 25

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 25행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4710_상주시_경상북도.xls (지역: 상주시)
WARNING *** file size (301542) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 34

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 34행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4711_문경시_경상북도.xls (지역: 문경시)
WARNING *** file size (202173) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4712_예천군_경상북도.xls (지역: 예천군)
WARNING *** file size (181844) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 22

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 22행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4713_경산시_경상북도.xls (지역: 경산시)
WARNING *** file size (212186) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 25

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 25행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4714_청도군_경상북도.xls (지역: 청도군)
WARNING *** file size (139678) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4715_고령군_경상북도.xls (지역: 고령군)
WARNING *** file size (119423) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 10

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 10행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4716_성주군_경상북도.xls (지역: 성주군)
WARNING *** file size (149543) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4717_칠곡군_경상북도.xls (지역: 칠곡군)
WARNING *** file size (119500) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 10

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 10행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4718_군위군_경상북도.xls (지역: 군위군)
WARNING *** file size (129244) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 11

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 11행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4719_의성군_경상북도.xls (지역: 의성군)
WARNING *** file size (241656) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 28

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 28행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4720_청송군_경상북도.xls (지역: 청송군)
WARNING *** file size (129261) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 11

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 11행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4721_영양군_경상북도.xls (지역: 영양군)
WARNING *** file size (109495) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 9

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 9행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4722_영덕군_경상북도.xls (지역: 영덕군)
WARNING *** file size (139651) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4723_봉화군_경상북도.xls (지역: 봉화군)
WARNING *** file size (139673) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4724_울진군_경상북도.xls (지역: 울진군)
WARNING *** file size (139707) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 14
데이터 행 수: 12

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 12행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 24개 파일
  - 실패: 0개 파일
  - 최종 크기: 24행 x 15열

In [30]:
gyeongbuk_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n박명재,한나라당\n김관용,column_7,계,무효\n투표수,기권수,column_11,column_12,column_13
0,포항시북구,NaN,합계,"190,449",NaN,"105,458","25,052","78,490",NaN,"103,542","1,916","84,991",NaN,NaN,0.0
1,포항시남구,NaN,합계,"191,369",NaN,"106,552","28,285","76,190",NaN,"104,475","2,077","84,817",NaN,NaN,0.0
2,울릉군,NaN,합계,"8,429",NaN,"7,197","1,978","5,034",NaN,"7,012",185,"1,232",NaN,NaN,0.0
3,경주시,NaN,합계,"210,980",NaN,"126,368","24,020","99,188",NaN,"123,208","3,160","84,612",NaN,NaN,0.0
4,김천시,NaN,합계,"110,274",NaN,"75,345","13,759","59,700",NaN,"73,459","1,886","34,929",NaN,NaN,0.0
5,안동시,NaN,합계,"134,448",NaN,"86,104","20,188","63,435",NaN,"83,623","2,481","48,344",NaN,NaN,0.0
6,구미시,NaN,합계,"269,226",NaN,"132,377","31,617","98,851",NaN,"130,468","1,909","136,849",NaN,NaN,0.0
7,영주시,NaN,합계,"93,247",NaN,"63,459","13,339","48,518",NaN,"61,857","1,602","29,788",NaN,NaN,0.0
8,영천시,NaN,합계,"86,235",NaN,"55,405","15,816","37,956",NaN,"53,772","1,633","30,830",NaN,NaN,0.0
9,상주시,NaN,합계,"88,983",NaN,"63,161","13,414","47,741",NaN,"61,155","2,006","25,822",NaN,NaN,0.0
10,문경시,NaN,합계,"62,743",NaN,"45,426","8,244","35,909",NaN,"44,153","1,273","17,317",NaN,NaN,0.0
11,예천군,NaN,합계,"42,780",NaN,"33,333","6,502","25,693",NaN,"32,195","1,138","9,447",NaN,NaN,0.0
12,경산시,NaN,합계,"175,092",NaN,"86,525","17,373","67,371",NaN,"84,744","1,781","88,567",NaN,NaN,0.0
13,청도군,NaN,합계,"39,951",NaN,"29,829","6,176","22,708",NaN,"28,884",945,"10,122",NaN,NaN,0.0
14,고령군,NaN,합계,"28,906",NaN,"20,678","4,704","15,279",NaN,"19,983",695,"8,228",NaN,NaN,0.0
15,성주군,NaN,합계,"38,867",NaN,"27,061","5,787","20,333",NaN,"26,120",941,"11,806",NaN,NaN,0.0
16,칠곡군,NaN,합계,"82,468",NaN,"44,214","10,846","32,355",NaN,"43,201","1,013","38,254",NaN,NaN,0.0
17,군위군,NaN,합계,"23,767",NaN,"18,447","4,387","13,338",NaN,"17,725",722,"5,320",NaN,NaN,0.0
18,의성군,NaN,합계,"55,083",NaN,"41,615","8,735","31,453",NaN,"40,188","1,427","13,468",NaN,NaN,0.0
19,청송군,NaN,합계,"24,481",NaN,"18,778","5,375","12,710",NaN,"18,085",693,"5,703",NaN,NaN,0.0
20,영양군,NaN,합계,"17,011",NaN,"13,680","4,124","9,033",NaN,"13,157",523,"3,331",NaN,NaN,0.0
21,영덕군,NaN,합계,"37,578",NaN,"27,226","6,156","20,243",NaN,"26,399",827,"10,352",NaN,NaN,0.0
22,봉화군,NaN,합계,"30,652",NaN,"23,132","5,627","16,850",NaN,"22,477",655,"7,520",NaN,NaN,0.0
23,울진군,NaN,합계,"44,690",NaN,"32,972","8,854","22,985",NaN,"31,839","1,133","11,718",NaN,NaN,0.0


## Gyeongnam

In [31]:
gyeongnam_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/48_경남"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/48_경남
------------------------------------------------------------
폴더에서 20개 파일 발견

처리 중: 4801_창원시_경상남도.xls (지역: 창원시)
WARNING *** file size (139944) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4802_마산시_경상남도.xls (지역: 마산시)
WARNING *** file size (270610) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 49

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 49행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4803_진주시_경상남도.xls (지역: 진주시)
WARNING *** file size (304105) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 54

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 54행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4804_진해시_경상남도.xls (지역: 진해시)
WARNING *** file size (139746) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4805_통영시_경상남도.xls (지역: 통영시)
WARNING *** file size (166550) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 28

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 28행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4806_고성군_경상남도.xls (지역: 고성군)
WARNING *** file size (139498) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4807_사천시_경상남도.xls (지역: 사천시)
WARNING *** file size (139669) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4808_김해시_경상남도.xls (지역: 김해시)
WARNING *** file size (160017) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 27

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 27행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4809_밀양시_경상남도.xls (지역: 밀양시)
WARNING *** file size (153117) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 26

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 26행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4810_거제시_경상남도.xls (지역: 거제시)
WARNING *** file size (146431) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 25

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 25행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4811_의령군_경상남도.xls (지역: 의령군)
WARNING *** file size (132773) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 23

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 23행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4812_함안군_경상남도.xls (지역: 함안군)
WARNING *** file size (103448) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4813_창녕군_경상남도.xls (지역: 창녕군)
WARNING *** file size (139613) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 24

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 24행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4814_양산시_경상남도.xls (지역: 양산시)
WARNING *** file size (90184) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 11

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 11행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4815_하동군_경상남도.xls (지역: 하동군)
WARNING *** file size (132869) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 23

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 23행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4816_남해군_경상남도.xls (지역: 남해군)
WARNING *** file size (103429) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4817_함양군_경상남도.xls (지역: 함양군)
WARNING *** file size (103439) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4818_산청군_경상남도.xls (지역: 산청군)
WARNING *** file size (103441) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 13

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 13행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4819_거창군_경상남도.xls (지역: 거창군)
WARNING *** file size (125594) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 22

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 22행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4820_합천군_경상남도.xls (지역: 합천군)
WARNING *** file size (153048) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 16
데이터 행 수: 26

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 26행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 20개 파일
  - 실패: 0개 파일
  - 최종 크기: 20행 x 17열

In [32]:
gyeongnam_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n김두관,한나라당\n김태호,민주노동당\n문성현,국민중심당\n김재주,column_9,계,무효\n투표수,기권수,column_13,column_14,column_15
0,창원시,NaN,합계,"356,493",NaN,"184,115","38,627","112,369","30,193","1,431",NaN,"182,620","1,495","172,378",NaN,NaN,0.0
1,마산시,NaN,합계,"326,663",NaN,"171,791","31,539","122,814","14,066","1,476",NaN,"169,895","1,896","154,872",NaN,NaN,0.0
2,진주시,NaN,합계,"252,537",NaN,"145,232","50,737","77,772","12,912","1,691",NaN,"143,112","2,120","107,305",NaN,NaN,0.0
3,진해시,NaN,합계,"118,111",NaN,"70,223","15,379","46,643","6,344",751,NaN,"69,117","1,106","47,888",NaN,NaN,0.0
4,통영시,NaN,합계,"102,469",NaN,"60,728","13,684","41,786","3,423",827,NaN,"59,720","1,008","41,741",NaN,NaN,0.0
5,고성군,NaN,합계,"46,167",NaN,"33,469","7,661","21,513","2,686",754,NaN,"32,614",855,"12,698",NaN,NaN,0.0
6,사천시,NaN,합계,"86,136",NaN,"57,392","15,408","35,061","4,718",962,NaN,"56,149","1,243","28,744",NaN,NaN,0.0
7,김해시,NaN,합계,"315,263",NaN,"150,966","47,354","87,632","12,929","1,213",NaN,"149,128","1,838","164,297",NaN,NaN,0.0
8,밀양시,NaN,합계,"90,362",NaN,"58,412","15,879","36,650","3,844",825,NaN,"57,198","1,214","31,950",NaN,NaN,0.0
9,거제시,NaN,합계,"142,095",NaN,"75,632","17,024","42,568","14,055",765,NaN,"74,412","1,220","66,463",NaN,NaN,0.0
10,의령군,NaN,합계,"26,675",NaN,"21,741","4,518","13,236","2,163",890,NaN,"20,807",934,"4,934",NaN,NaN,0.0
11,함안군,NaN,합계,"48,706",NaN,"34,252","6,619","22,544","3,331",767,NaN,"33,261",991,"14,454",NaN,NaN,0.0
12,창녕군,NaN,합계,"52,848",NaN,"37,285","7,546","25,192","2,653",857,NaN,"36,248","1,037","15,563",NaN,NaN,0.0
13,양산시,NaN,합계,"162,544",NaN,"86,355","19,427","56,004","8,191","1,099",NaN,"84,721","1,634","76,189",NaN,NaN,0.0
14,하동군,NaN,합계,"42,978",NaN,"31,435","11,354","16,059","2,284",796,NaN,"30,493",942,"11,543",NaN,NaN,0.0
15,남해군,NaN,합계,"42,965",NaN,"32,988","18,947","11,830",906,480,NaN,"32,163",825,"9,977",NaN,NaN,0.0
16,함양군,NaN,합계,"34,178",NaN,"27,657","6,492","15,797","3,724",976,NaN,"26,989",668,"6,521",NaN,NaN,0.0
17,산청군,NaN,합계,"30,952",NaN,"23,787","4,934","15,303","2,199",666,NaN,"23,102",685,"7,165",NaN,NaN,0.0
18,거창군,NaN,합계,"50,916",NaN,"35,360","4,256","27,893","1,812",620,NaN,"34,581",779,"15,556",NaN,NaN,0.0
19,합천군,NaN,합계,"46,207",NaN,"34,995","5,752","23,711","3,390","1,060",NaN,"33,913","1,082","11,212",NaN,NaN,0.0


## Jeju

In [33]:
jeju_4th = process_4th_governor_election_batch(
    user="sw1kwon",
    repo="korean-elections",
    folder="original/Local_Elections_Governor/4th_2006/49_제주"
)

4대 지방선거 데이터 일괄 처리 시작
저장소: sw1kwon/korean-elections
폴더: original/Local_Elections_Governor/4th_2006/49_제주
------------------------------------------------------------
폴더에서 4개 파일 발견

처리 중: 4901_제주시_제주도.xls (지역: 제주시)
WARNING *** file size (212874) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 29

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 29행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4902_북제주군_제주도.xls (지역: 북제주군)
WARNING *** file size (101411) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 10

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 10행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4903_서귀포시_제주도.xls (지역: 서귀포시)
WARNING *** file size (145824) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 21

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 21행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

처리 중: 4904_남제주군_제주도.xls (지역: 남제주군)
WARNING *** file size (76550) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
헤더 행: 4행 ~ 6행
생성된 컬럼 수: 15
데이터 행 수: 7

'읍면동명' 컬럼 발견: 읍면동명
필터링 전: 7행 → 필터링 후: 1행
  ✓ 완료: 1행 추가

============================================================
일괄 처리 완료:
  - 성공: 4개 파일
  - 실패: 0개 파일
  - 최종 크기: 4행 x 16열

In [34]:
jeju_4th

,구시군명,column_0,읍면동명,선거인수,column_3,투표수,후보자별 득표수_열린우리당\n진철훈,한나라당\n현명관,무소속\n김태환,column_8,계,무효\n투표수,기권수,column_12,column_13,column_14
0,제주시,NaN,합계,"218,768",NaN,"138,717","22,748","56,423","58,722",NaN,"137,893",824,"80,051",NaN,NaN,0.0
1,북제주군,NaN,합계,"74,387",NaN,"51,650","10,793","16,607","23,455",NaN,"50,855",795,"22,737",NaN,NaN,0.0
2,서귀포시,NaN,합계,"62,209",NaN,"43,561","5,087","19,930","18,098",NaN,"43,115",446,"18,648",NaN,NaN,0.0
3,남제주군,NaN,합계,"56,498",NaN,"43,075","5,706","19,814","16,969",NaN,"42,489",586,"13,423",NaN,NaN,0.0

# Batch CSV Files to ZIP

In [ ]:
import zipfile
import glob

# Find all CSV files in current directory
csv_files = glob.glob('*.csv')

# Create ZIP file
with zipfile.ZipFile('all_csv_files.zip', 'w') as zipf:
   for file in csv_files:
       zipf.write(file)
       print(f"Added: {file}")  # Show progress

print(f"Total {len(csv_files)} files compressed.")